server = 'sql.civica.local'  
database_especialidades = 'esnowflake'  
username_especialidades = 'esnowflake'  
password_especialidades = 'TkUPu2xHB9a$'

database_sql = 'SQL_EN_LLAMAS'  
username_sql = 'sqlonfire'  
password_sql = 'ES*Cr~#vqaBq'  

# Add these lines to your existing secrets.toml
admin_user = "admin_civica"  # Choose your admin username
admin_password = "@FQAR$2w5QMBud"  # Choose a secure password